// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    LsResult: typeof import('./src/components/LsResult.vue')['default']
    TerminalCommand: typeof import('./src/components/TerminalCommand.vue')['default']
  }
}

export { }
